nelmio_api_doc:
    documentation:
        info:
            title: API documentation
            description: Documentation for the Products management example
            version: 1.0.0
    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/docs$)

